### ISSUE TITLE
Not sure how to use this, please help?

### ISSUE THREAD

**Issue by SenkaWolf** [carterbush/discord-call-log#1]
Hey Carter,

I am trying to use this code for the exact same reason in your read me file however I've never used Visual Studio or C# before. I tried to run it, well I think I was trying to run it but got the following error message https://i.senkawolf.com/uFyW22 

Is there something I am doing wrong or is there an error with the code? Any assistance would be greatly appreciated.

**Comment by carterbush** [comment]
Nearly one year later, I've rewritten this so hopefully it's easier to use now.
